spring:
  application:
    name: user-service-client
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/userservicelab_db
    username: pavel
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8191