server:
  port: 8888

spring:
  application:
    name: config-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndreyIgnatev/ConfigServerLab.git
          username: ignatevmailwork@gmail.com
          password: KKnD1945$
          default-label: main
          search-paths: "{application}"