server:
  port: 8888
spring:
  application:
    name: config-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    config:
      server:
        git:
          uri:
          username: ignatevmailwork@gmail.com
          password: KKnD1945$
          default-label: main
          search-paths: "{application}"
  datasource:
    driver-class-name: org.postgresql.Driver
  properties:
    DB_URL: jdbc:postgresql://db:5432/postgres
    DB_USER: pavel
    DB_PASSWORD: password