server:
  port: 8888
spring:
  application:
    name: config-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndreyIgnatev/ConfigServerLab.git
          username: ignatevmailwork@gmail.com
          password: KKnD1945$
          default-label: main
          search-paths: "{application}"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  properties:
    DB_URL: jdbc:postgresql://db:5432/postgres
    DB_USER: pavel
    DB_PASSWORD: password
  dependencies:
    - org.postgresql:postgresql:42.3.3