spring:
  application:
    name: deposit-service-client
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/depositservicelab_db
    username: pavel
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.104:8761/eureka/  # Используем IP хост-машины
    register-with-eureka: false  # Если не нужно регистрировать этот сервис в Eureka
    fetch-registry: true

server:
  port: 8192

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#
#server:
#  port: 8192